<?php 
require_once __DIR__.'/MyInterface.php';
require_once __DIR__.'/ClassA.php';
// Anonymus Class --
            // php me Anonymus Function ke saath annonymus class bhi hoti hai es class ka koi name nahi hota hai
// creating Anonymus class ----
$obj= new class(/**aap esme same constructor argument paas kar sakte hai */1,2,3)/* extends MyClass*/ implements MyInterface {
    #body of the class
    //use MyTraits;---aap esme bhi traits aur class, interface ko extende aur implements kar sakte ho
    public function __construct(
        public int $x, 
        public int $y, 
        public int $z
    ){
        //constructor body
    }
};//yaha per terminater lagana nesessesry hai
var_dump($obj);//output---
/*
object(class@anonymous)#1 (3) {
  ["x"]=>
  int(1)
  ["y"]=>
  int(2)
  ["z"]=>
  int(3)
}
//___________________________________________________________________________________
 */
/**
 * esme aap regular class ki tarah hi inheritans use kar sakte ho
 * aur interface aur traits ko bhi same vaise hi use kar sakte hai jaise regular class me use kiya jata hai.
 * -> qki eska naam nahi defin kiya jata hai to eska matlab eska naam null(hai hi nahi) nahi hai eska naam hota hai
 */
// eska naam engin(php) khud defin karti hai->
echo "The name of Anonymus Class is ".get_class($obj)."  generated by PHP Engin".PHP_EOL;
var_dump(get_class($obj));
//______________________________________________________________________________
// aap Anonymus class ki type ko change (type hanting) nahi kar sakte hi qki eski koi type (name) nahi hota 
// aur class ka naam ho class ka type hota hai 
// parantu aap esme kishi interface ko jod kar uske saath eski type hanting kar sakte hai Interface jodte hi 
// anonymous class ki type hanting hokar vah Interface ho jata jai jise joda gaya hai
// Example--
function foo(MyInterface $hentedObject){
    var_dump($hentedObject);
} 
foo($obj);//eski jarurat nahi hai pur kar sakte hi
// out put--
/*
object(MyInterface@anonymous)#1 (3) {
  ["x"]=>
  int(1)
  ["y"]=>
  int(2)
  ["z"]=>
  int(3)
}
  //_______________________________________________________________________________________________________________
 */ // LAST AUR MOST IMPORTANT IN ANONYMOUS CLASS
 // aap kishi regular class me bhi anonyamus class ko jod sakte hai
 // eske liya aao "ClassA" ko dkhe baki ki information vahi hai---- 
 $Obj = new AnonymousClass\ClassA(1,2);
 var_dump($Obj->foo());
 $Obj-> bar();


?>